# SPDX-FileCopyrightText: 2026 Yifei Sun
# SPDX-License-Identifier: FSL-1.1-ALv2

version = 1

[[annotations]]
path = "flake.lock"
precedence = "override"
SPDX-FileCopyrightText = ["2026 Nick Cao", "2026 Yifei Sun"]
SPDX-License-Identifier = "MIT AND FSL-1.1-ALv2"

[[annotations]]
path = ["integration/org-key.pem", "integration/org-pub.pem"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Nick Cao"
SPDX-License-Identifier = "MIT"
